version: "3"
services:
  web:
    build: web
    ports:
      - "80:80"
    volumes:
      - www-home:/var/www
    restart: always

  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "https://dataone.org"
      VIRT_Server_DirsAllowed: "/data/dumps"
    volumes:
      - virtuoso-home:/data
    ports:
      - "127.0.0.1:8890:8890"

  worker:
    build: worker
    volumes:
      - ./d1lod:/d1lod
    environment:
      - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
    restart: always

  scheduler:
    build: scheduler
    volumes:
      - ./d1lod:/d1lod
    environment:
      - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
    restart: always

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - redis-home:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

  rqdashboard:
    build: rqdashboard
    links:
      - redis
    ports:
      - "127.0.0.1:9181:9181"

volumes:
  www-home: {}
  virtuoso-home: {}
  redis-home: {}
